# Use postgres/example user/password credentials
version: '3.1'
services:
# This is the db definition
  xald_db:
      container_name: xald_db
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
#Add everything to the same network so the containers can talk to each other
      networks:
        - postgres
      volumes:
#Create and fill the db on create
        - ./dataset:/docker-entrypoint-initdb.d
        
  xald_app:
      container_name: xald_app
      build: .
      ports:
        - "4000:4000"
      environment:
#The URL from the above DB with the credentials defined on top
        - DB_URL=postgresql://postgres:example@xald_db:5432/postgres
      depends_on:
        - xald_db
#Add everything to the same network so the containers can talk to each other
      networks:
        - postgres
  
  centos:
    image: centos
#Add everything to the same network so the containers can talk to each other
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
