# Use postgres/example user/password credentials
version: '3.1'
services:
  flask_db:
      container_name: flask_db
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      ports:
        - 5432:5432
      networks:
        - postgres
      volumes:
        - ./dataset:/docker-entrypoint-initdb.d
        #- pgdata:/var/lib/postgresql/data
  flask_app:
      container_name: flask_app
      build: .
      ports:
        - "4000:4000"
      environment:
        - DB_URL=postgresql://postgres:example@flask_db:5432/postgres
      depends_on:
        - flask_db
      networks:
        - postgres
  
  centos:
    image: centos
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
#volumes:
#  pgdata: {}